version: '3.7'

services:

  postgress:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    networks:
      - backend-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRESS_DB}
    ports:
      - 5432
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=backend-net
        ### Traefik-v2
        - traefik.tcp.routers.postgress-tcp.rule=HostSNI(`*`)
        - traefik.tcp.routers.postgress-tcp.entrypoints=postgress
        - traefik.tcp.routers.postgress-tcp.service=postgress-proxy
        - traefik.tcp.services.postgress-proxy.loadbalancer.server.port=5432

volumes:
  postgres_data:

networks:
  backend-net:
    external: true